a=int(input("enter 1 number:"))
b=int(input("enter 2 number :"))
print("the addition:", a+b)
print("the subtraction",a-b)
print("themultiplication:",a*b)
print("the division:",a/b)
print("the floor division",a//b)
print("the modulus",a%b)
print("the exponentiation:",a^b)
