a=int(input("enter age of 1 voter:"))
b=int(input("enter age of 2 voter"))
print("a=b:",a==b)
print("a<b:",a<b)
print("a>b:",a>b)
print("a!=b",a!=b)
print("a>=b:",a>=b)
print("a<=b:",a<=b)
print("both are eligible:",(a>=18)&(b>=18))